Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ixnetwork in /home/geordie/.local/lib/python3.10/site-packages (9.30.2212.7)
Requirement already satisfied: backports.ssl>=0.0.9 in /home/geordie/.local/lib/python3.10/site-packages (from ixnetwork) (0.0.9)
Requirement already satisfied: backports.ssl-match-hostname>=3.5.0.1 in /home/geordie/.local/lib/python3.10/site-packages (from ixnetwork) (3.7.0.1)
Requirement already satisfied: pyopenssl>=17.5.0 in /home/geordie/.local/lib/python3.10/site-packages (from ixnetwork) (23.0.0)
Requirement already satisfied: requests>=2.18.4 in /home/geordie/.local/lib/python3.10/site-packages (from ixnetwork) (2.31.0)
Requirement already satisfied: websocket-client>=0.47.0 in /usr/lib/python3/dist-packages (from ixnetwork) (0.53.0)
Requirement already satisfied: cryptography<40,>=38.0.0 in /home/geordie/.local/lib/python3.10/site-packages (from pyopenssl>=17.5.0->ixnetwork) (39.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/geordie/.local/lib/python3.10/site-packages (from requests>=2.18.4->ixnetwork) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.18.4->ixnetwork) (2.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/geordie/.local/lib/python3.10/site-packages (from requests>=2.18.4->ixnetwork) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.18.4->ixnetwork) (2019.11.28)
Requirement already satisfied: cffi>=1.12 in /home/geordie/.local/lib/python3.10/site-packages (from cryptography<40,>=38.0.0->pyopenssl>=17.5.0->ixnetwork) (1.15.1)
Requirement already satisfied: pycparser in /home/geordie/.local/lib/python3.10/site-packages (from cffi>=1.12->cryptography<40,>=38.0.0->pyopenssl>=17.5.0->ixnetwork) (2.21)
